// 80-session elite CX library seed data
// Modality defaults to 'turbo' unless specified

export const sessionLibrarySeed = [
  // ─── TURBO / WATTBIKE — Z2 ENDURANCE (6) ───────────────────────────────────
  {
    slug: 'turbo-z2-60',
    name: 'Z2 Endurance 60min',
    modality: 'turbo',
    power_zone: 2,
    power_pct_low: 56,
    power_pct_high: 75,
    tss_estimate: 55,
    rpe_target: 5,
    duration_mins: 60,
    valid_phases: ['Foundation', 'Base', 'Base2', 'Build', 'Build2', 'Taper', 'Recovery'],
    warmup: '10min easy spin building from 50% to 65% FTP',
    main_set: '40min steady Z2 at 56-75% FTP. Maintain smooth cadence 85-95rpm. Conversational pace throughout.',
    cooldown: '10min easy spin reducing to 50% FTP',
    coaching_notes: "Foundation of all aerobic adaptation. If you can't hold a conversation you're going too hard.",
    requires_turbo: true,
    requires_wattbike: false,
    requires_power_meter: false,
    requires_cx_terrain: false,
    is_active: true,
  },
  {
    slug: 'turbo-z2-90',
    name: 'Z2 Endurance 90min',
    modality: 'turbo',
    power_zone: 2,
    power_pct_low: 56,
    power_pct_high: 75,
    tss_estimate: 80,
    rpe_target: 5,
    duration_mins: 90,
    valid_phases: ['Foundation', 'Base', 'Base2', 'Build'],
    warmup: '15min easy',
    main_set: '60min steady Z2 56-75% FTP, cadence 85-95rpm',
    cooldown: '15min easy',
    coaching_notes: 'Extended aerobic stimulus. Key for mitochondrial density.',
    requires_turbo: true,
    requires_wattbike: false,
    requires_power_meter: false,
    requires_cx_terrain: false,
    is_active: true,
  },
  {
    slug: 'turbo-z2-120',
    name: 'Z2 Endurance 120min with Tempo',
    modality: 'turbo',
    power_zone: 2,
    power_pct_low: 56,
    power_pct_high: 90,
    tss_estimate: 115,
    rpe_target: 6,
    duration_mins: 120,
    valid_phases: ['Base', 'Base2'],
    warmup: '15min easy',
    main_set: '70min Z2 at 56-75% FTP then 2×10min tempo at 76-90% FTP with 5min Z2 between',
    cooldown: '10min easy',
    coaching_notes: 'Introduces tempo stimulus into long endurance ride. Only when Z2 base is solid.',
    requires_turbo: true,
    requires_wattbike: false,
    requires_power_meter: false,
    requires_cx_terrain: false,
    is_active: true,
  },
  {
    slug: 'turbo-z2-cadence',
    name: 'Z2 Cadence Work 60min',
    modality: 'turbo',
    power_zone: 2,
    power_pct_low: 56,
    power_pct_high: 75,
    tss_estimate: 58,
    rpe_target: 5,
    duration_mins: 60,
    valid_phases: ['Foundation', 'Base', 'Base2'],
    warmup: '10min easy',
    main_set: '40min Z2 with 6×5min high cadence efforts at 100-110rpm (keep power in Z2), 2min normal cadence between',
    cooldown: '10min easy',
    coaching_notes: 'Improves neuromuscular efficiency. Essential for CX where cadence varies constantly.',
    requires_turbo: true,
    requires_wattbike: false,
    requires_power_meter: false,
    requires_cx_terrain: false,
    is_active: true,
  },
  {
    slug: 'turbo-z2-recovery',
    name: 'Recovery Spin 45min',
    modality: 'turbo',
    power_zone: 1,
    power_pct_low: 45,
    power_pct_high: 55,
    tss_estimate: 30,
    rpe_target: 3,
    duration_mins: 45,
    valid_phases: ['Recovery', 'Taper', 'Peak'],
    warmup: '5min very easy',
    main_set: '35min easy spin under 55% FTP. No hard efforts. Just flush the legs.',
    cooldown: '5min easy',
    coaching_notes: 'Active recovery only. If legs are very fatigued consider complete rest instead.',
    requires_turbo: true,
    requires_wattbike: false,
    requires_power_meter: false,
    requires_cx_terrain: false,
    is_active: true,
  },
  {
    slug: 'turbo-endurance-progressive',
    name: 'Progressive Endurance 75min',
    modality: 'turbo',
    power_zone: 2,
    power_pct_low: 56,
    power_pct_high: 83,
    tss_estimate: 75,
    rpe_target: 6,
    duration_mins: 75,
    valid_phases: ['Base', 'Base2', 'Build'],
    warmup: '10min easy',
    main_set: '3 blocks of 20min: Block 1 at 56-65% FTP, Block 2 at 66-75% FTP, Block 3 at 76-83% FTP',
    cooldown: '5min easy',
    coaching_notes: 'Progressive overload teaches body to sustain higher intensities over time.',
    requires_turbo: true,
    requires_wattbike: false,
    requires_power_meter: false,
    requires_cx_terrain: false,
    is_active: true,
  },

  // ─── TURBO / WATTBIKE — THRESHOLD (6) ──────────────────────────────────────
  {
    slug: 'turbo-threshold-2x20',
    name: 'Threshold 2×20min',
    modality: 'turbo',
    power_zone: 4,
    power_pct_low: 95,
    power_pct_high: 105,
    tss_estimate: 95,
    rpe_target: 8,
    duration_mins: 55,
    valid_phases: ['Base2', 'Build', 'Build2'],
    warmup: '15min building to Z3',
    main_set: '2×20min at 95-105% FTP, 5min easy spin recovery between. Hold power steady — do not fade in second interval.',
    cooldown: '10min easy',
    coaching_notes: 'Gold standard threshold session. If power drops >5% in set 2, FTP may be set too high.',
    requires_turbo: true,
    requires_wattbike: false,
    requires_power_meter: true,
    requires_cx_terrain: false,
    is_active: true,
  },
  {
    slug: 'turbo-threshold-3x15',
    name: 'Threshold 3×15min',
    modality: 'turbo',
    power_zone: 4,
    power_pct_low: 95,
    power_pct_high: 100,
    tss_estimate: 100,
    rpe_target: 8,
    duration_mins: 65,
    valid_phases: ['Base2', 'Build', 'Build2'],
    warmup: '15min building',
    main_set: '3×15min at 95-100% FTP, 5min recovery between sets',
    cooldown: '10min easy',
    coaching_notes: 'Higher volume than 2×20 at slightly lower intensity. Good for building threshold endurance.',
    requires_turbo: true,
    requires_wattbike: false,
    requires_power_meter: true,
    requires_cx_terrain: false,
    is_active: true,
  },
  {
    slug: 'turbo-threshold-over-under',
    name: 'Over-Unders',
    modality: 'turbo',
    power_zone: 4,
    power_pct_low: 95,
    power_pct_high: 108,
    tss_estimate: 90,
    rpe_target: 8,
    duration_mins: 65,
    valid_phases: ['Build', 'Build2', 'Peak'],
    warmup: '15min',
    main_set: '4×10min over-unders: 3min at 95% FTP then 2min at 108% FTP, repeat twice per set. 5min recovery between sets.',
    cooldown: '10min',
    coaching_notes: 'Teaches lactate clearance under fatigue. Excellent CX-specific session.',
    requires_turbo: true,
    requires_wattbike: false,
    requires_power_meter: true,
    requires_cx_terrain: false,
    is_active: true,
  },
  {
    slug: 'turbo-threshold-sweetspot',
    name: 'Sweetspot 3×12min',
    modality: 'turbo',
    power_zone: 3,
    power_pct_low: 88,
    power_pct_high: 93,
    tss_estimate: 85,
    rpe_target: 7,
    duration_mins: 57,
    valid_phases: ['Base', 'Base2', 'Build'],
    warmup: '15min',
    main_set: '3×12min at 88-93% FTP (sweetspot), 5min recovery between',
    cooldown: '10min',
    coaching_notes: 'High stimulus for aerobic adaptation with lower recovery cost than threshold. Ideal mid-week session.',
    requires_turbo: true,
    requires_wattbike: false,
    requires_power_meter: false,
    requires_cx_terrain: false,
    is_active: true,
  },
  {
    slug: 'turbo-threshold-ramp',
    name: 'Ramp to Threshold',
    modality: 'turbo',
    power_zone: 4,
    power_pct_low: 76,
    power_pct_high: 100,
    tss_estimate: 80,
    rpe_target: 7,
    duration_mins: 50,
    valid_phases: ['Base', 'Base2'],
    warmup: '10min easy',
    main_set: '20min progressive ramp from 76% to 100% FTP building by 1% per minute, then 10min hold at 100% FTP',
    cooldown: '10min easy',
    coaching_notes: 'Gradual build teaches pacing control. Good introduction to threshold work.',
    requires_turbo: true,
    requires_wattbike: false,
    requires_power_meter: false,
    requires_cx_terrain: false,
    is_active: true,
  },
  {
    slug: 'turbo-threshold-extended',
    name: 'Extended Threshold 40min',
    modality: 'turbo',
    power_zone: 4,
    power_pct_low: 92,
    power_pct_high: 96,
    tss_estimate: 110,
    rpe_target: 8,
    duration_mins: 65,
    valid_phases: ['Build2', 'Peak'],
    warmup: '15min',
    main_set: '1×40min at 92-96% FTP. Maintain even power. Mental toughness session.',
    cooldown: '10min',
    coaching_notes: 'Elite-level threshold endurance. Only assign when athlete has 4+ weeks threshold training.',
    requires_turbo: true,
    requires_wattbike: false,
    requires_power_meter: true,
    requires_cx_terrain: false,
    experience_levels: ['elite'],
    is_active: true,
  },

  // ─── TURBO / WATTBIKE — VO2MAX (6) ─────────────────────────────────────────
  {
    slug: 'turbo-vo2-5x4',
    name: 'VO2max 5×4min',
    modality: 'turbo',
    power_zone: 5,
    power_pct_low: 110,
    power_pct_high: 120,
    tss_estimate: 90,
    rpe_target: 9,
    duration_mins: 60,
    valid_phases: ['Build', 'Build2', 'Peak'],
    warmup: '15min building with 2×1min openers at 110%',
    main_set: '5×4min at 110-120% FTP, 4min easy recovery between. Start conservatively — set 4 and 5 should be hardest.',
    cooldown: '10min easy',
    coaching_notes: 'Classic VO2max session. Sustainable hard effort — not a sprint.',
    requires_turbo: true,
    requires_wattbike: false,
    requires_power_meter: true,
    requires_cx_terrain: false,
    is_active: true,
  },
  {
    slug: 'turbo-vo2-8x3',
    name: 'VO2max 8×3min',
    modality: 'turbo',
    power_zone: 5,
    power_pct_low: 112,
    power_pct_high: 118,
    tss_estimate: 95,
    rpe_target: 9,
    duration_mins: 63,
    valid_phases: ['Build', 'Build2', 'Peak'],
    warmup: '15min with openers',
    main_set: '8×3min at 112-118% FTP, 3min recovery. High volume VO2 work.',
    cooldown: '10min',
    coaching_notes: 'Higher repetitions build VO2 time-in-zone. Last 3 sets should feel very hard.',
    requires_turbo: true,
    requires_wattbike: false,
    requires_power_meter: true,
    requires_cx_terrain: false,
    is_active: true,
  },
  {
    slug: 'turbo-vo2-tabata',
    name: 'Tabata VO2',
    modality: 'turbo',
    power_zone: 6,
    power_pct_low: 130,
    power_pct_high: 150,
    tss_estimate: 75,
    rpe_target: 10,
    duration_mins: 60,
    valid_phases: ['Build2', 'Peak'],
    warmup: '20min thorough warmup',
    main_set: '4 sets of Tabata: 8×(20s maximal at 130%+ FTP / 10s complete rest). 5min easy between sets.',
    cooldown: '10min easy',
    coaching_notes: 'Extreme intensity. Only for experienced athletes. Directly mirrors CX effort pattern.',
    requires_turbo: true,
    requires_wattbike: false,
    requires_power_meter: true,
    requires_cx_terrain: false,
    experience_levels: ['elite'],
    is_active: true,
  },
  {
    slug: 'turbo-vo2-40-20',
    name: '40-20s Intervals',
    modality: 'turbo',
    power_zone: 6,
    power_pct_low: 120,
    power_pct_high: 130,
    tss_estimate: 80,
    rpe_target: 9,
    duration_mins: 55,
    valid_phases: ['Build', 'Build2', 'Peak'],
    warmup: '15min with openers',
    main_set: '15×(40s at 120-130% FTP / 20s easy). 5min easy between 2 sets of 15.',
    cooldown: '10min',
    coaching_notes: 'Short work:rest trains ability to push hard repeatedly. CX-specific.',
    requires_turbo: true,
    requires_wattbike: false,
    requires_power_meter: true,
    requires_cx_terrain: false,
    is_active: true,
  },
  {
    slug: 'turbo-vo2-pyramid',
    name: 'VO2 Pyramid',
    modality: 'turbo',
    power_zone: 5,
    power_pct_low: 110,
    power_pct_high: 120,
    tss_estimate: 85,
    rpe_target: 9,
    duration_mins: 55,
    valid_phases: ['Build', 'Build2'],
    warmup: '15min',
    main_set: 'Pyramid: 1/2/3/4/3/2/1min all at 115% FTP. Equal rest between (1min rest after 1min, 4min rest after 4min). Total work 16min.',
    cooldown: '10min',
    coaching_notes: 'Variable duration builds mental and physical adaptability.',
    requires_turbo: true,
    requires_wattbike: false,
    requires_power_meter: true,
    requires_cx_terrain: false,
    is_active: true,
  },
  {
    slug: 'turbo-vo2-3x8',
    name: 'VO2 3×8min',
    modality: 'turbo',
    power_zone: 5,
    power_pct_low: 108,
    power_pct_high: 115,
    tss_estimate: 95,
    rpe_target: 8,
    duration_mins: 57,
    valid_phases: ['Build', 'Build2', 'Peak'],
    warmup: '15min',
    main_set: '3×8min at 108-115% FTP, 5min recovery. Longer VO2 intervals build aerobic ceiling.',
    cooldown: '10min',
    coaching_notes: 'Bridges gap between threshold and short VO2 intervals. Excellent all-round session.',
    requires_turbo: true,
    requires_wattbike: false,
    requires_power_meter: true,
    requires_cx_terrain: false,
    is_active: true,
  },

  // ─── TURBO / WATTBIKE — SPRINT / NEUROMUSCULAR (4) ─────────────────────────
  {
    slug: 'turbo-sprint-seated',
    name: 'Seated Sprints 10×10s',
    modality: 'turbo',
    power_zone: 7,
    power_pct_low: 150,
    power_pct_high: 200,
    tss_estimate: 60,
    rpe_target: 9,
    duration_mins: 60,
    valid_phases: ['Build', 'Build2', 'Peak'],
    warmup: '20min thorough warmup',
    main_set: '10×10s maximal seated sprints, 3min full recovery between. Focus on peak power output.',
    cooldown: '10min easy',
    coaching_notes: 'Neuromuscular power. Keep seated to isolate leg drive. Numbers should be consistent sprint to sprint.',
    requires_turbo: true,
    requires_wattbike: false,
    requires_power_meter: true,
    requires_cx_terrain: false,
    is_active: true,
  },
  {
    slug: 'turbo-sprint-standing',
    name: 'Standing Start Sprints',
    modality: 'turbo',
    power_zone: 7,
    power_pct_low: 150,
    power_pct_high: 200,
    tss_estimate: 65,
    rpe_target: 9,
    duration_mins: 58,
    valid_phases: ['Build2', 'Peak'],
    warmup: '20min',
    main_set: '8×15s standing start sprints from near-stop, 4min recovery. Simulate race start acceleration.',
    cooldown: '10min',
    coaching_notes: 'Race start specific. Explosive acceleration from low speed — critical for CX.',
    requires_turbo: true,
    requires_wattbike: false,
    requires_power_meter: true,
    requires_cx_terrain: false,
    is_active: true,
  },
  {
    slug: 'turbo-sprint-mixed',
    name: 'Mixed Sprints 6×30s',
    modality: 'turbo',
    power_zone: 7,
    power_pct_low: 140,
    power_pct_high: 180,
    tss_estimate: 70,
    rpe_target: 9,
    duration_mins: 60,
    valid_phases: ['Build2', 'Peak', 'Taper'],
    warmup: '20min',
    main_set: '6×30s all-out efforts, 5min full recovery between. Z2 riding before and after.',
    cooldown: '10min easy spin',
    coaching_notes: 'Longer sprint duration builds both peak power and sprint endurance.',
    requires_turbo: true,
    requires_wattbike: false,
    requires_power_meter: false,
    requires_cx_terrain: false,
    is_active: true,
  },
  {
    slug: 'turbo-map-test',
    name: 'MAP Test 5min',
    modality: 'turbo',
    power_zone: 6,
    power_pct_low: 100,
    power_pct_high: 150,
    tss_estimate: 55,
    rpe_target: 10,
    duration_mins: 45,
    valid_phases: ['Base', 'Build'],
    warmup: '20min building, 3min at threshold',
    main_set: '5min maximal aerobic power test — go as hard as you can sustain for exactly 5 minutes. Record average power.',
    cooldown: '15min very easy',
    coaching_notes: 'Determines maximal aerobic power. Use result to calibrate VO2max interval targets.',
    requires_turbo: true,
    requires_wattbike: false,
    requires_power_meter: true,
    requires_cx_terrain: false,
    is_active: true,
  },

  // ─── TURBO / WATTBIKE — RACE SIMULATION (4) ────────────────────────────────
  {
    slug: 'turbo-race-sim-45',
    name: 'Race Simulation 45min',
    modality: 'turbo',
    power_zone: 5,
    power_pct_low: 85,
    power_pct_high: 130,
    tss_estimate: 100,
    rpe_target: 9,
    duration_mins: 70,
    valid_phases: ['Peak'],
    warmup: '15min building',
    main_set: '45min CX race simulation: follow a realistic CX power profile with surges to 130%+ on corners/barriers, Z4 on straights, brief Z2 recoveries. Average power should be ~85% FTP.',
    cooldown: '10min easy',
    coaching_notes: 'Replicate exact race physiological demands. Use a structured power file if available.',
    requires_turbo: true,
    requires_wattbike: false,
    requires_power_meter: true,
    requires_cx_terrain: false,
    is_active: true,
  },
  {
    slug: 'turbo-race-sim-60',
    name: 'Race Simulation 60min',
    modality: 'turbo',
    power_zone: 5,
    power_pct_low: 85,
    power_pct_high: 130,
    tss_estimate: 120,
    rpe_target: 9,
    duration_mins: 85,
    valid_phases: ['Peak'],
    warmup: '15min',
    main_set: '60min race simulation with structured surge pattern: 45s at 120-130% FTP every 3min simulating barriers/corners, remainder at Z3-Z4.',
    cooldown: '10min',
    coaching_notes: 'Extended race sim. Only when athlete has completed 45min version.',
    requires_turbo: true,
    requires_wattbike: false,
    requires_power_meter: true,
    requires_cx_terrain: false,
    experience_levels: ['elite'],
    is_active: true,
  },
  {
    slug: 'turbo-start-efforts',
    name: 'Race Start Efforts',
    modality: 'turbo',
    power_zone: 6,
    power_pct_low: 110,
    power_pct_high: 150,
    tss_estimate: 85,
    rpe_target: 9,
    duration_mins: 70,
    valid_phases: ['Peak', 'Taper'],
    warmup: '20min with openers',
    main_set: '6 race start simulations: 30s maximal sprint from standstill + 5min at race pace (105-115% FTP), 5min easy recovery between.',
    cooldown: '10min',
    coaching_notes: 'Combines explosive start with sustained race pace. Directly race-specific.',
    requires_turbo: true,
    requires_wattbike: false,
    requires_power_meter: false,
    requires_cx_terrain: false,
    is_active: true,
  },
  {
    slug: 'turbo-pre-race-openers',
    name: 'Pre-Race Openers (Turbo)',
    modality: 'turbo',
    power_zone: 3,
    power_pct_low: 55,
    power_pct_high: 110,
    tss_estimate: 45,
    rpe_target: 6,
    duration_mins: 45,
    valid_phases: ['Taper', 'Peak'],
    warmup: '15min easy',
    main_set: '4×30s at race pace (105-110% FTP), 3min easy between. Finish feeling activated not tired.',
    cooldown: '10min easy',
    coaching_notes: 'Day before race. Activates neuromuscular system without inducing fatigue.',
    requires_turbo: true,
    requires_wattbike: false,
    requires_power_meter: false,
    requires_cx_terrain: false,
    is_active: true,
  },

  // ─── TURBO / WATTBIKE — BENCHMARK (2) ──────────────────────────────────────
  {
    slug: 'turbo-benchmark-ftp',
    name: 'FTP Test 20min',
    modality: 'turbo',
    power_zone: 4,
    power_pct_low: 95,
    power_pct_high: 105,
    tss_estimate: 80,
    rpe_target: 10,
    duration_mins: 55,
    valid_phases: ['Foundation', 'Base'],
    warmup: '20min: 10min easy, 3min at tempo, 5min easy, 1min hard',
    main_set: '20min all-out time trial. Even pace — do not go out too hard. Record average power. FTP = average power × 0.95.',
    cooldown: '15min very easy',
    coaching_notes: 'Standard FTP test. Consistency in warmup protocol is essential for valid comparison.',
    requires_turbo: true,
    requires_wattbike: false,
    requires_power_meter: true,
    requires_cx_terrain: false,
    is_active: true,
  },
  {
    slug: 'turbo-benchmark-full',
    name: 'Full Benchmark Test',
    modality: 'turbo',
    power_zone: 5,
    power_pct_low: 95,
    power_pct_high: 200,
    tss_estimate: 95,
    rpe_target: 10,
    duration_mins: 80,
    valid_phases: ['Foundation', 'Base'],
    warmup: '20min thorough',
    main_set: '20min FTP test, 10min easy, 3min maximal test, 10min easy, 10s sprint test. Record all three numbers.',
    cooldown: '15min',
    coaching_notes: 'Full performance profile. FTP, VO2 power, and peak neuromuscular power in one session.',
    requires_turbo: true,
    requires_wattbike: false,
    requires_power_meter: true,
    requires_cx_terrain: false,
    is_active: true,
  },

  // ─── NORDIC INTERVALS — EARLY PREP 1:1.5 (4) ───────────────────────────────
  {
    slug: 'nordic-prep-20-30-x8',
    name: 'Nordic Prep 20/30s ×8',
    modality: 'nordic',
    power_zone: 6,
    power_pct_low: 120,
    power_pct_high: 135,
    tss_estimate: 65,
    rpe_target: 8,
    nordic_ratio: '1:1.5',
    nordic_sets: 4,
    nordic_work_secs: 20,
    nordic_rest_secs: 30,
    valid_phases: ['Base', 'Base2'],
    warmup: '10min easy jog/cycle',
    main_set: '4 sets of 8×(20s ON at 120-135% FTP / 30s complete rest). 3min easy between sets.',
    cooldown: '10min easy',
    coaching_notes: 'Entry-level Nordic protocol. 20s is short enough to maintain quality throughout.',
    requires_turbo: false,
    requires_wattbike: false,
    requires_power_meter: false,
    requires_cx_terrain: false,
    is_active: true,
  },
  {
    slug: 'nordic-prep-30-45-x6',
    name: 'Nordic Prep 30/45s ×6',
    modality: 'nordic',
    power_zone: 6,
    power_pct_low: 120,
    power_pct_high: 135,
    tss_estimate: 70,
    rpe_target: 8,
    nordic_ratio: '1:1.5',
    nordic_sets: 4,
    nordic_work_secs: 30,
    nordic_rest_secs: 45,
    valid_phases: ['Base', 'Base2'],
    warmup: '10min easy',
    main_set: '4 sets of 6×(30s ON / 45s rest). 3min between sets.',
    cooldown: '10min',
    coaching_notes: 'Progresses from 20-30 version. Longer work interval increases lactate challenge.',
    requires_turbo: false,
    requires_wattbike: false,
    requires_power_meter: false,
    requires_cx_terrain: false,
    is_active: true,
  },
  {
    slug: 'nordic-prep-20-30-x10',
    name: 'Nordic Prep 20/30s ×10',
    modality: 'nordic',
    power_zone: 6,
    power_pct_low: 120,
    power_pct_high: 135,
    tss_estimate: 72,
    rpe_target: 9,
    nordic_ratio: '1:1.5',
    nordic_sets: 3,
    nordic_work_secs: 20,
    nordic_rest_secs: 30,
    valid_phases: ['Base2'],
    warmup: '10min',
    main_set: '3 sets of 10×(20s ON / 30s rest). 3min between sets.',
    cooldown: '10min',
    coaching_notes: 'Volume progression from ×8. Maintain power through all reps.',
    requires_turbo: false,
    requires_wattbike: false,
    requires_power_meter: false,
    requires_cx_terrain: false,
    is_active: true,
  },
  {
    slug: 'nordic-prep-pyramid',
    name: 'Nordic Prep Pyramid',
    modality: 'nordic',
    power_zone: 6,
    power_pct_low: 120,
    power_pct_high: 135,
    tss_estimate: 68,
    rpe_target: 8,
    nordic_ratio: '1:1.5',
    valid_phases: ['Base', 'Base2'],
    warmup: '10min',
    main_set: '3 sets of pyramid: 10s/20s/30s/20s/10s ON with 1.5× rest each. 3min between sets.',
    cooldown: '10min',
    coaching_notes: 'Variable duration within 1:1.5 ratio. Psychologically engaging.',
    requires_turbo: false,
    requires_wattbike: false,
    requires_power_meter: false,
    requires_cx_terrain: false,
    is_active: true,
  },

  // ─── NORDIC INTERVALS — BUILD 1:1 (5) ──────────────────────────────────────
  {
    slug: 'nordic-build-30-30-x10',
    name: 'Nordic Build 30/30s ×10',
    modality: 'nordic',
    power_zone: 6,
    power_pct_low: 125,
    power_pct_high: 140,
    tss_estimate: 78,
    rpe_target: 9,
    nordic_ratio: '1:1',
    nordic_sets: 3,
    nordic_work_secs: 30,
    nordic_rest_secs: 30,
    valid_phases: ['Build'],
    warmup: '15min',
    main_set: '3 sets of 10×(30s ON at 125-140% FTP / 30s rest). 3min between sets.',
    cooldown: '10min',
    coaching_notes: '1:1 ratio increases demands significantly. Power should drop no more than 5% across sets.',
    requires_turbo: false,
    requires_wattbike: false,
    requires_power_meter: false,
    requires_cx_terrain: false,
    is_active: true,
  },
  {
    slug: 'nordic-build-40-40-x8',
    name: 'Nordic Build 40/40s ×8',
    modality: 'nordic',
    power_zone: 6,
    power_pct_low: 125,
    power_pct_high: 140,
    tss_estimate: 82,
    rpe_target: 9,
    nordic_ratio: '1:1',
    nordic_sets: 3,
    nordic_work_secs: 40,
    nordic_rest_secs: 40,
    valid_phases: ['Build'],
    warmup: '15min',
    main_set: '3 sets of 8×(40s ON / 40s rest). 3min between sets.',
    cooldown: '10min',
    coaching_notes: 'Longer work intervals. Very demanding — only on fresh legs.',
    requires_turbo: false,
    requires_wattbike: false,
    requires_power_meter: false,
    requires_cx_terrain: false,
    is_active: true,
  },
  {
    slug: 'nordic-build-30-30-x12',
    name: 'Nordic Build 30/30s ×12',
    modality: 'nordic',
    power_zone: 6,
    power_pct_low: 125,
    power_pct_high: 138,
    tss_estimate: 85,
    rpe_target: 9,
    nordic_ratio: '1:1',
    nordic_sets: 3,
    nordic_work_secs: 30,
    nordic_rest_secs: 30,
    valid_phases: ['Build', 'Build2'],
    warmup: '15min',
    main_set: '3 sets of 12×(30s ON / 30s rest). 3min between sets.',
    cooldown: '10min',
    coaching_notes: 'Volume progression from ×10. 36 total reps is significant workload.',
    requires_turbo: false,
    requires_wattbike: false,
    requires_power_meter: false,
    requires_cx_terrain: false,
    is_active: true,
  },
  {
    slug: 'nordic-build-tabata-cx',
    name: 'Nordic CX Tabata',
    modality: 'nordic',
    power_zone: 7,
    power_pct_low: 130,
    power_pct_high: 150,
    tss_estimate: 75,
    rpe_target: 10,
    nordic_ratio: '1:0.5',
    nordic_sets: 4,
    nordic_work_secs: 20,
    nordic_rest_secs: 10,
    valid_phases: ['Build2', 'Peak'],
    warmup: '20min thorough',
    main_set: '4 sets of 8×(20s maximal / 10s rest). 5min between sets. CX-specific Tabata.',
    cooldown: '10min',
    coaching_notes: 'Extreme intensity mimicking CX demands. Requires excellent base fitness.',
    requires_turbo: false,
    requires_wattbike: false,
    requires_power_meter: false,
    requires_cx_terrain: false,
    experience_levels: ['intermediate', 'elite'],
    is_active: true,
  },
  {
    slug: 'nordic-build-mixed',
    name: 'Nordic Build Mixed Duration',
    modality: 'nordic',
    power_zone: 6,
    power_pct_low: 120,
    power_pct_high: 140,
    tss_estimate: 80,
    rpe_target: 9,
    nordic_ratio: '1:1',
    valid_phases: ['Build'],
    warmup: '15min',
    main_set: '3 sets of alternating: 20s/40s/20s/40s/20s ON with equal rest. 3min between sets.',
    cooldown: '10min',
    coaching_notes: 'Variable work duration within 1:1 ratio keeps muscles and mind engaged.',
    requires_turbo: false,
    requires_wattbike: false,
    requires_power_meter: false,
    requires_cx_terrain: false,
    is_active: true,
  },

  // ─── NORDIC INTERVALS — INTENSIFICATION 1:0.75 (5) ─────────────────────────
  {
    slug: 'nordic-intense-40-30-x8',
    name: 'Nordic Intense 40/30s ×8',
    modality: 'nordic',
    power_zone: 6,
    power_pct_low: 128,
    power_pct_high: 143,
    tss_estimate: 88,
    rpe_target: 9,
    nordic_ratio: '1:0.75',
    nordic_sets: 3,
    nordic_work_secs: 40,
    nordic_rest_secs: 30,
    valid_phases: ['Build2'],
    warmup: '15min with openers',
    main_set: '3 sets of 8×(40s ON / 30s rest). 4min between sets.',
    cooldown: '10min',
    coaching_notes: 'Reduced rest increases challenge. Lactate accumulation across each set.',
    requires_turbo: false,
    requires_wattbike: false,
    requires_power_meter: false,
    requires_cx_terrain: false,
    is_active: true,
  },
  {
    slug: 'nordic-intense-60-45-x6',
    name: 'Nordic Intense 60/45s ×6',
    modality: 'nordic',
    power_zone: 6,
    power_pct_low: 125,
    power_pct_high: 140,
    tss_estimate: 92,
    rpe_target: 9,
    nordic_ratio: '1:0.75',
    nordic_sets: 3,
    nordic_work_secs: 60,
    nordic_rest_secs: 45,
    valid_phases: ['Build2', 'Peak'],
    warmup: '15min',
    main_set: '3 sets of 6×(60s ON / 45s rest). 4min between sets.',
    cooldown: '10min',
    coaching_notes: '60s efforts are race-duration specific. Very high quality required.',
    requires_turbo: false,
    requires_wattbike: false,
    requires_power_meter: false,
    requires_cx_terrain: false,
    is_active: true,
  },
  {
    slug: 'nordic-intense-30-22-x10',
    name: 'Nordic Intense 30/22s ×10',
    modality: 'nordic',
    power_zone: 6,
    power_pct_low: 128,
    power_pct_high: 143,
    tss_estimate: 86,
    rpe_target: 9,
    nordic_ratio: '1:0.75',
    nordic_sets: 3,
    nordic_work_secs: 30,
    nordic_rest_secs: 22,
    valid_phases: ['Build2'],
    warmup: '15min',
    main_set: '3 sets of 10×(30s ON / 22s rest). 4min between sets.',
    cooldown: '10min',
    coaching_notes: 'Short rest creates cumulative fatigue across each set.',
    requires_turbo: false,
    requires_wattbike: false,
    requires_power_meter: false,
    requires_cx_terrain: false,
    is_active: true,
  },
  {
    slug: 'nordic-intense-cx-lap',
    name: 'Nordic CX Lap Effort',
    modality: 'nordic',
    power_zone: 6,
    power_pct_low: 125,
    power_pct_high: 140,
    tss_estimate: 90,
    rpe_target: 9,
    nordic_ratio: '1:0.75',
    nordic_work_secs: 45,
    nordic_rest_secs: 34,
    valid_phases: ['Peak'],
    warmup: '15min',
    main_set: '3 sets of 6×(45s race pace / 34s rest). 4min between sets. Simulate CX lap effort.',
    cooldown: '10min',
    coaching_notes: 'Designed to match CX lap duration and effort pattern.',
    requires_turbo: false,
    requires_wattbike: false,
    requires_power_meter: false,
    requires_cx_terrain: false,
    is_active: true,
  },
  {
    slug: 'nordic-intense-extended',
    name: 'Nordic Intense Extended',
    modality: 'nordic',
    power_zone: 6,
    power_pct_low: 125,
    power_pct_high: 140,
    tss_estimate: 98,
    rpe_target: 10,
    nordic_ratio: '1:0.75',
    nordic_sets: 4,
    nordic_work_secs: 60,
    nordic_rest_secs: 45,
    valid_phases: ['Peak'],
    warmup: '20min',
    main_set: '4 sets of 6×(60s ON / 45s rest). 4min between sets.',
    cooldown: '10min',
    coaching_notes: 'Elite only. Maximum volume at 1:0.75 ratio.',
    requires_turbo: false,
    requires_wattbike: false,
    requires_power_meter: false,
    requires_cx_terrain: false,
    experience_levels: ['elite'],
    is_active: true,
  },

  // ─── NORDIC INTERVALS — RACE SPECIFIC 1:0.5 (6) ────────────────────────────
  {
    slug: 'nordic-race-60-30-x6',
    name: 'Nordic Race 60/30s ×6',
    modality: 'nordic',
    power_zone: 6,
    power_pct_low: 130,
    power_pct_high: 145,
    tss_estimate: 88,
    rpe_target: 10,
    nordic_ratio: '1:0.5',
    nordic_sets: 3,
    nordic_work_secs: 60,
    nordic_rest_secs: 30,
    valid_phases: ['Peak'],
    warmup: '20min',
    main_set: '3 sets of 6×(60s ON / 30s rest). 5min between sets.',
    cooldown: '10min',
    coaching_notes: '1:0.5 ratio is race-specific. Minimum rest forces adaptation to incomplete recovery.',
    requires_turbo: false,
    requires_wattbike: false,
    requires_power_meter: false,
    requires_cx_terrain: false,
    is_active: true,
  },
  {
    slug: 'nordic-race-90-45-x4',
    name: 'Nordic Race 90/45s ×4',
    modality: 'nordic',
    power_zone: 6,
    power_pct_low: 125,
    power_pct_high: 140,
    tss_estimate: 92,
    rpe_target: 10,
    nordic_ratio: '1:0.5',
    nordic_sets: 3,
    nordic_work_secs: 90,
    nordic_rest_secs: 45,
    valid_phases: ['Peak'],
    warmup: '20min',
    main_set: '3 sets of 4×(90s ON / 45s rest). 5min between sets.',
    cooldown: '10min',
    coaching_notes: 'Longest individual work intervals in the programme. Brutal and necessary.',
    requires_turbo: false,
    requires_wattbike: false,
    requires_power_meter: false,
    requires_cx_terrain: false,
    experience_levels: ['intermediate', 'elite'],
    is_active: true,
  },
  {
    slug: 'nordic-race-cx-effort',
    name: 'Nordic Race CX Effort Blocks',
    modality: 'nordic',
    power_zone: 5,
    power_pct_low: 105,
    power_pct_high: 120,
    tss_estimate: 95,
    rpe_target: 9,
    nordic_ratio: '1:0.5',
    valid_phases: ['Peak'],
    warmup: '20min',
    main_set: '3 sets of 4×3min race pace effort / 90s rest. 5min between sets.',
    cooldown: '10min',
    coaching_notes: 'Extended race effort blocks. Builds sustained high-intensity capacity.',
    requires_turbo: false,
    requires_wattbike: false,
    requires_power_meter: false,
    requires_cx_terrain: false,
    is_active: true,
  },
  {
    slug: 'nordic-race-erratic',
    name: 'Nordic Race Erratic Efforts',
    modality: 'nordic',
    power_zone: 6,
    power_pct_low: 120,
    power_pct_high: 145,
    tss_estimate: 90,
    rpe_target: 9,
    nordic_ratio: '1:0.5',
    valid_phases: ['Peak'],
    warmup: '20min',
    main_set: '30min of erratic race simulation: random 20-90s efforts at 120-145% FTP with 0.5× rest after each. Coach or app determines effort duration.',
    cooldown: '10min',
    coaching_notes: 'Unpredictable effort duration mimics true race demands.',
    requires_turbo: false,
    requires_wattbike: false,
    requires_power_meter: false,
    requires_cx_terrain: false,
    is_active: true,
  },
  {
    slug: 'nordic-race-championship',
    name: 'Nordic Championship Prep',
    modality: 'nordic',
    power_zone: 5,
    power_pct_low: 100,
    power_pct_high: 120,
    tss_estimate: 105,
    rpe_target: 9,
    nordic_ratio: '1:0.5',
    valid_phases: ['Peak'],
    warmup: '20min',
    main_set: '3×12min race pace blocks at 100-120% FTP, 6min recovery between.',
    cooldown: '10min',
    coaching_notes: 'Championship preparation. Extended race-pace blocks.',
    requires_turbo: false,
    requires_wattbike: false,
    requires_power_meter: false,
    requires_cx_terrain: false,
    experience_levels: ['elite'],
    is_active: true,
  },
  {
    slug: 'nordic-race-final-tune',
    name: 'Nordic Race Week Sharpener',
    modality: 'nordic',
    power_zone: 6,
    power_pct_low: 120,
    power_pct_high: 140,
    tss_estimate: 55,
    rpe_target: 8,
    nordic_ratio: '1:0.5',
    valid_phases: ['Taper'],
    warmup: '15min',
    main_set: '4×30s at race pace + 2×60s at race pace, full recovery between all efforts.',
    cooldown: '10min',
    coaching_notes: 'Race week sharpener. Maintain race pace feel without inducing fatigue.',
    requires_turbo: false,
    requires_wattbike: false,
    requires_power_meter: false,
    requires_cx_terrain: false,
    is_active: true,
  },

  // ─── OUTDOOR — LONG ENDURANCE (5) ───────────────────────────────────────────
  {
    slug: 'outdoor-z2-2hr',
    name: 'Outdoor Z2 2hr',
    modality: 'outdoor_road',
    power_zone: 2,
    power_pct_low: 56,
    power_pct_high: 75,
    tss_estimate: 110,
    rpe_target: 5,
    duration_mins: 120,
    valid_phases: ['Base', 'Base2', 'Build'],
    warmup: '15min easy',
    main_set: '1hr 45min steady Z2 road riding. Find quiet roads with minimal stops.',
    cooldown: 'natural',
    coaching_notes: 'Weekend long ride. Aerobic base cornerstone.',
    requires_turbo: false,
    requires_wattbike: false,
    requires_power_meter: false,
    requires_cx_terrain: false,
    is_active: true,
  },
  {
    slug: 'outdoor-z2-3hr',
    name: 'Outdoor Z2 3hr',
    modality: 'outdoor_road',
    power_zone: 2,
    power_pct_low: 56,
    power_pct_high: 75,
    tss_estimate: 160,
    rpe_target: 6,
    duration_mins: 180,
    valid_phases: ['Base', 'Base2'],
    warmup: '15min easy',
    main_set: '2hr 40min Z2. Nutrition every 45min essential.',
    cooldown: '5min easy spin',
    coaching_notes: 'Volume is the stimulus. Resist urge to push harder.',
    requires_turbo: false,
    requires_wattbike: false,
    requires_power_meter: false,
    requires_cx_terrain: false,
    is_active: true,
  },
  {
    slug: 'outdoor-z2-4hr',
    name: 'Outdoor Z2 4hr',
    modality: 'outdoor_road',
    power_zone: 2,
    power_pct_low: 56,
    power_pct_high: 75,
    tss_estimate: 210,
    rpe_target: 6,
    duration_mins: 240,
    valid_phases: ['Base'],
    warmup: '20min easy',
    main_set: '3hr 20min Z2. Long slow distance. Eat every 40-45min.',
    cooldown: 'natural',
    coaching_notes: 'Only for athletes building significant aerobic base. Requires excellent nutrition strategy.',
    requires_turbo: false,
    requires_wattbike: false,
    requires_power_meter: false,
    requires_cx_terrain: false,
    experience_levels: ['intermediate', 'elite'],
    is_active: true,
  },
  {
    slug: 'outdoor-endurance-mixed',
    name: 'Outdoor Endurance Mixed',
    modality: 'outdoor_road',
    power_zone: 3,
    power_pct_low: 56,
    power_pct_high: 90,
    tss_estimate: 140,
    rpe_target: 6,
    duration_mins: 150,
    valid_phases: ['Base2', 'Build'],
    warmup: '15min',
    main_set: '2hr Z2 with 3×10min tempo climbs at 76-90% FTP when terrain allows',
    cooldown: '15min easy',
    coaching_notes: 'Use natural terrain for tempo efforts. Don\'t force tempo on flat ground.',
    requires_turbo: false,
    requires_wattbike: false,
    requires_power_meter: false,
    requires_cx_terrain: false,
    is_active: true,
  },
  {
    slug: 'outdoor-recovery-spin',
    name: 'Outdoor Recovery Spin',
    modality: 'outdoor_road',
    power_zone: 1,
    power_pct_low: 45,
    power_pct_high: 55,
    tss_estimate: 50,
    rpe_target: 3,
    duration_mins: 75,
    valid_phases: ['Recovery', 'Taper'],
    warmup: 'natural',
    main_set: '60-90min very easy riding. Stop at cafes. This is not training — it\'s recovery.',
    cooldown: 'natural',
    coaching_notes: 'True recovery. No hard efforts whatsoever.',
    requires_turbo: false,
    requires_wattbike: false,
    requires_power_meter: false,
    requires_cx_terrain: false,
    is_active: true,
  },

  // ─── OUTDOOR — TEMPO/THRESHOLD (4) ──────────────────────────────────────────
  {
    slug: 'outdoor-tempo-90',
    name: 'Outdoor Tempo 2×20min',
    modality: 'outdoor_road',
    power_zone: 3,
    power_pct_low: 76,
    power_pct_high: 90,
    tss_estimate: 100,
    rpe_target: 7,
    duration_mins: 90,
    valid_phases: ['Base2', 'Build'],
    warmup: '20min easy',
    main_set: '2×20min tempo at 76-90% FTP on rolling terrain, 10min easy between',
    cooldown: '15min easy',
    coaching_notes: 'Use roads with consistent gradient for tempo. Hills make pacing difficult.',
    requires_turbo: false,
    requires_wattbike: false,
    requires_power_meter: false,
    requires_cx_terrain: false,
    is_active: true,
  },
  {
    slug: 'outdoor-threshold-climbs',
    name: 'Outdoor Threshold Climbs',
    modality: 'outdoor_road',
    power_zone: 4,
    power_pct_low: 95,
    power_pct_high: 105,
    tss_estimate: 105,
    rpe_target: 8,
    duration_mins: 100,
    valid_phases: ['Build', 'Build2'],
    warmup: '20min',
    main_set: '4×8min threshold efforts on climbs at 95-105% FTP, 5min easy descent recovery',
    cooldown: '15min',
    coaching_notes: 'Climbs naturally encourage threshold effort. Choose 8-10min climbs.',
    requires_turbo: false,
    requires_wattbike: false,
    requires_power_meter: false,
    requires_cx_terrain: false,
    is_active: true,
  },
  {
    slug: 'outdoor-sweetspot-ride',
    name: 'Outdoor Sweetspot 3×15min',
    modality: 'outdoor_road',
    power_zone: 3,
    power_pct_low: 88,
    power_pct_high: 93,
    tss_estimate: 120,
    rpe_target: 7,
    duration_mins: 120,
    valid_phases: ['Build', 'Build2'],
    warmup: '15min',
    main_set: '2hr with 3×15min sweetspot at 88-93% FTP, 10min easy between',
    cooldown: '15min',
    coaching_notes: 'Outdoor sweetspot. Higher total TSS than turbo version due to terrain variation.',
    requires_turbo: false,
    requires_wattbike: false,
    requires_power_meter: false,
    requires_cx_terrain: false,
    is_active: true,
  },
  {
    slug: 'outdoor-cx-course-threshold',
    name: 'CX Course Threshold Laps',
    modality: 'outdoor_cx',
    power_zone: 4,
    power_pct_low: 90,
    power_pct_high: 105,
    tss_estimate: 110,
    rpe_target: 8,
    duration_mins: 90,
    valid_phases: ['Build', 'Build2'],
    warmup: '20min',
    main_set: '4×10min threshold laps on CX course, 5min recovery between',
    cooldown: '10min',
    coaching_notes: 'Combines technical CX skills with threshold physiology.',
    requires_turbo: false,
    requires_wattbike: false,
    requires_power_meter: false,
    requires_cx_terrain: true,
    is_active: true,
  },

  // ─── OUTDOOR — CX SPECIFIC (5) ───────────────────────────────────────────────
  {
    slug: 'outdoor-cx-race-sim',
    name: 'CX Race Simulation',
    modality: 'outdoor_cx',
    power_zone: 5,
    power_pct_low: 85,
    power_pct_high: 130,
    tss_estimate: 110,
    rpe_target: 9,
    duration_mins: 75,
    valid_phases: ['Peak'],
    warmup: '20min',
    main_set: '45-60min CX course race simulation. Push hard on barriers, corners, run-ups. Aim for realistic race pace.',
    cooldown: '15min easy',
    coaching_notes: 'No shortcuts — full commitment every lap.',
    requires_turbo: false,
    requires_wattbike: false,
    requires_power_meter: false,
    requires_cx_terrain: true,
    is_active: true,
  },
  {
    slug: 'outdoor-cx-technical',
    name: 'CX Technical Skills',
    modality: 'outdoor_cx',
    power_zone: 2,
    power_pct_low: 50,
    power_pct_high: 75,
    tss_estimate: 70,
    rpe_target: 5,
    duration_mins: 100,
    valid_phases: ['Base', 'Base2', 'Build'],
    warmup: '10min easy',
    main_set: '90min technical riding on CX course. Focus on line choice, dismounts, corners. Low intensity, high skill focus.',
    cooldown: 'natural',
    coaching_notes: 'Technical skill work at low intensity. Quality of movement not power output.',
    requires_turbo: false,
    requires_wattbike: false,
    requires_power_meter: false,
    requires_cx_terrain: true,
    is_active: true,
  },
  {
    slug: 'outdoor-cx-starts',
    name: 'CX Race Starts Practice',
    modality: 'outdoor_cx',
    power_zone: 7,
    power_pct_low: 130,
    power_pct_high: 200,
    tss_estimate: 75,
    rpe_target: 9,
    duration_mins: 70,
    valid_phases: ['Peak', 'Taper'],
    warmup: '20min',
    main_set: '8 race starts on grass: maximal 30s sprint + 2min at race pace, full recovery (5min) between',
    cooldown: '10min easy',
    coaching_notes: 'Grass start practice. Perfect clip-in, body position, first pedal strokes.',
    requires_turbo: false,
    requires_wattbike: false,
    requires_power_meter: false,
    requires_cx_terrain: true,
    is_active: true,
  },
  {
    slug: 'outdoor-cx-recon',
    name: 'CX Course Reconnaissance',
    modality: 'outdoor_cx',
    power_zone: 1,
    power_pct_low: 45,
    power_pct_high: 65,
    tss_estimate: 40,
    rpe_target: 4,
    duration_mins: 45,
    valid_phases: ['Peak', 'Taper'],
    warmup: 'natural',
    main_set: '30-45min course reconnaissance. Walk difficult sections. Note line choices, barriers, mud patches. Easy riding throughout.',
    cooldown: 'natural',
    coaching_notes: 'Pre-race recon. Information gathering not training.',
    requires_turbo: false,
    requires_wattbike: false,
    requires_power_meter: false,
    requires_cx_terrain: true,
    is_active: true,
  },
  {
    slug: 'outdoor-cx-sandpit',
    name: 'CX Sandpit Practice',
    modality: 'outdoor_cx',
    power_zone: 2,
    power_pct_low: 50,
    power_pct_high: 75,
    tss_estimate: 55,
    rpe_target: 6,
    duration_mins: 60,
    valid_phases: ['Base', 'Build', 'Peak'],
    warmup: '15min',
    main_set: '45min dedicated sandpit practice: entry speed, momentum maintenance, exit. 20+ passes through sandpit.',
    cooldown: '10min',
    coaching_notes: 'Sand is a differentiator in CX. Dedicated practice pays dividends.',
    requires_turbo: false,
    requires_wattbike: false,
    requires_power_meter: false,
    requires_cx_terrain: true,
    is_active: true,
  },

  // ─── OUTDOOR — PRE/POST RACE (4) ────────────────────────────────────────────
  {
    slug: 'outdoor-pre-race-openers',
    name: 'Pre-Race Openers (Outdoor)',
    modality: 'outdoor_road',
    power_zone: 3,
    power_pct_low: 55,
    power_pct_high: 110,
    tss_estimate: 45,
    rpe_target: 6,
    duration_mins: 45,
    valid_phases: ['Taper', 'Peak'],
    warmup: '15min very easy',
    main_set: '3×30s at race pace (105-110% FTP), 5min easy between. Finish feeling sharp.',
    cooldown: '10min easy',
    coaching_notes: 'Day before race. Activate without fatiguing. Total ride should feel easy.',
    requires_turbo: false,
    requires_wattbike: false,
    requires_power_meter: false,
    requires_cx_terrain: false,
    is_active: true,
  },
  {
    slug: 'outdoor-post-race-flush',
    name: 'Post-Race Flush Spin',
    modality: 'outdoor_road',
    power_zone: 1,
    power_pct_low: 45,
    power_pct_high: 55,
    tss_estimate: 30,
    rpe_target: 3,
    duration_mins: 40,
    valid_phases: ['Recovery', 'Taper'],
    warmup: 'natural',
    main_set: '30-45min very easy flushing spin day after race. No hard efforts.',
    cooldown: 'natural',
    coaching_notes: 'Speeds recovery. Gentle movement better than complete rest for most athletes.',
    requires_turbo: false,
    requires_wattbike: false,
    requires_power_meter: false,
    requires_cx_terrain: false,
    is_active: true,
  },
  {
    slug: 'outdoor-race-week-short',
    name: 'Race Week Short Activation',
    modality: 'outdoor_road',
    power_zone: 2,
    power_pct_low: 55,
    power_pct_high: 75,
    tss_estimate: 35,
    rpe_target: 5,
    duration_mins: 35,
    valid_phases: ['Taper'],
    warmup: '5min easy',
    main_set: '25min easy with 4×15s race pace efforts, 3min easy between',
    cooldown: '5min easy',
    coaching_notes: 'Race week activation. Short and sharp.',
    requires_turbo: false,
    requires_wattbike: false,
    requires_power_meter: false,
    requires_cx_terrain: false,
    is_active: true,
  },
  {
    slug: 'outdoor-cx-full-race',
    name: 'Full CX Race',
    modality: 'outdoor_cx',
    power_zone: 5,
    power_pct_low: 85,
    power_pct_high: 130,
    tss_estimate: 120,
    rpe_target: 10,
    duration_mins: 75,
    valid_phases: ['Peak', 'Taper'],
    warmup: 'structured 20min race warmup',
    main_set: 'Full UCI or national CX race (40-60min). Race hard from gun to tape.',
    cooldown: '15min easy spin + cool down',
    coaching_notes: 'Log actual races here. Include course conditions, result, and key notes.',
    requires_turbo: false,
    requires_wattbike: false,
    requires_power_meter: false,
    requires_cx_terrain: true,
    is_active: true,
  },

  // ─── SKILLS — DISMOUNT / REMOUNT (3) ─────────────────────────────────────────
  {
    slug: 'skills-dismount-basic',
    name: 'Dismount & Remount Basics',
    modality: 'skills',
    power_zone: null,
    power_pct_low: null,
    power_pct_high: null,
    tss_estimate: 30,
    rpe_target: 4,
    duration_mins: 35,
    valid_phases: ['Foundation', 'Base'],
    warmup: '10min easy ride',
    main_set: '20min walking pace dismount and remount drills. 30 reps each side. Focus on technique not speed.',
    cooldown: '5min easy',
    coaching_notes: 'Master technique before speed. Sloppy dismounts cause crashes.',
    requires_turbo: false,
    requires_wattbike: false,
    requires_power_meter: false,
    requires_cx_terrain: false,
    is_active: true,
  },
  {
    slug: 'skills-dismount-speed',
    name: 'Dismount Speed Development',
    modality: 'skills',
    power_zone: null,
    power_pct_low: null,
    power_pct_high: null,
    tss_estimate: 40,
    rpe_target: 6,
    duration_mins: 40,
    valid_phases: ['Base', 'Base2', 'Build'],
    warmup: '10min',
    main_set: '30min progressive speed dismount practice. Build from slow to race pace. Timed sequences of 10 reps.',
    cooldown: '5min',
    coaching_notes: 'Once technique is solid, build speed. Time each set of 10.',
    requires_turbo: false,
    requires_wattbike: false,
    requires_power_meter: false,
    requires_cx_terrain: false,
    is_active: true,
  },
  {
    slug: 'skills-dismount-barriers',
    name: 'Full Barrier Sequence',
    modality: 'skills',
    power_zone: null,
    power_pct_low: null,
    power_pct_high: null,
    tss_estimate: 50,
    rpe_target: 7,
    duration_mins: 55,
    valid_phases: ['Build', 'Build2', 'Peak'],
    warmup: '15min',
    main_set: '40min full barrier sequence at race speed. Include approach, dismount, barriers, remount, acceleration. 20+ full sequences.',
    cooldown: '10min',
    coaching_notes: 'Full race speed with barriers. This is the complete skill.',
    requires_turbo: false,
    requires_wattbike: false,
    requires_power_meter: false,
    requires_cx_terrain: true,
    is_active: true,
  },

  // ─── SKILLS — CORNERING (3) ──────────────────────────────────────────────────
  {
    slug: 'skills-cornering-basic',
    name: 'Cornering Basics',
    modality: 'skills',
    power_zone: null,
    power_pct_low: null,
    power_pct_high: null,
    tss_estimate: 30,
    rpe_target: 4,
    duration_mins: 40,
    valid_phases: ['Foundation', 'Base'],
    warmup: '10min',
    main_set: '30min off-camber entry and exit drills at slow speed. Focus on body position and weight distribution.',
    cooldown: '5min',
    coaching_notes: 'Off-camber is CX-specific. Take time here.',
    requires_turbo: false,
    requires_wattbike: false,
    requires_power_meter: false,
    requires_cx_terrain: true,
    is_active: true,
  },
  {
    slug: 'skills-cornering-speed',
    name: 'Race-Speed Cornering',
    modality: 'skills',
    power_zone: null,
    power_pct_low: null,
    power_pct_high: null,
    tss_estimate: 45,
    rpe_target: 6,
    duration_mins: 60,
    valid_phases: ['Build', 'Build2', 'Peak'],
    warmup: '15min',
    main_set: '45min race-speed cornering on varied surfaces. Include off-camber, flat, slippery.',
    cooldown: '10min',
    coaching_notes: 'Progressive speed build. Don\'t exceed comfortable limit.',
    requires_turbo: false,
    requires_wattbike: false,
    requires_power_meter: false,
    requires_cx_terrain: true,
    is_active: true,
  },
  {
    slug: 'skills-cornering-wet',
    name: 'Wet & Mud Cornering',
    modality: 'skills',
    power_zone: null,
    power_pct_low: null,
    power_pct_high: null,
    tss_estimate: 40,
    rpe_target: 6,
    duration_mins: 55,
    valid_phases: ['Base', 'Build', 'Peak'],
    warmup: '10min',
    main_set: '40min wet and mud cornering practice. Body position adjustments for low traction.',
    cooldown: '10min',
    coaching_notes: 'Wet cornering is completely different skill. Must be practised specifically.',
    requires_turbo: false,
    requires_wattbike: false,
    requires_power_meter: false,
    requires_cx_terrain: true,
    is_active: true,
  },

  // ─── SKILLS — CARRYING & RUNNING (3) ─────────────────────────────────────────
  {
    slug: 'skills-run-carry-basic',
    name: 'Bike Carry Technique',
    modality: 'skills',
    power_zone: null,
    power_pct_low: null,
    power_pct_high: null,
    tss_estimate: 35,
    rpe_target: 5,
    duration_mins: 30,
    valid_phases: ['Foundation', 'Base'],
    warmup: '10min easy jog',
    main_set: '20min bike carry technique: shoulder position, hand placement, running posture.',
    cooldown: '5min walk',
    coaching_notes: 'Correct shoulder position prevents fatigue and injury.',
    requires_turbo: false,
    requires_wattbike: false,
    requires_power_meter: false,
    requires_cx_terrain: false,
    is_active: true,
  },
  {
    slug: 'skills-run-carry-speed',
    name: 'Carry Speed Development',
    modality: 'skills',
    power_zone: null,
    power_pct_low: null,
    power_pct_high: null,
    tss_estimate: 50,
    rpe_target: 7,
    duration_mins: 40,
    valid_phases: ['Base', 'Build', 'Peak'],
    warmup: '10min',
    main_set: '30min run with bike at increasing pace. 8×100m carry at race pace with walk recovery.',
    cooldown: '5min',
    coaching_notes: 'Build carry pace systematically. Technique degrades when fatigued.',
    requires_turbo: false,
    requires_wattbike: false,
    requires_power_meter: false,
    requires_cx_terrain: false,
    is_active: true,
  },
  {
    slug: 'skills-run-stairs',
    name: 'Stair & Run-Up Practice',
    modality: 'skills',
    power_zone: null,
    power_pct_low: null,
    power_pct_high: null,
    tss_estimate: 55,
    rpe_target: 7,
    duration_mins: 40,
    valid_phases: ['Build', 'Build2', 'Peak'],
    warmup: '15min',
    main_set: '20min stair and steep run-up practice. 15 full reps of the run-up section.',
    cooldown: '10min',
    coaching_notes: 'Run-up pace is often a race differentiator. Practice the specific run-up if possible.',
    requires_turbo: false,
    requires_wattbike: false,
    requires_power_meter: false,
    requires_cx_terrain: true,
    is_active: true,
  },

  // ─── SKILLS — SAND & MUD (2) ─────────────────────────────────────────────────
  {
    slug: 'skills-sand-technique',
    name: 'Sand Riding Technique',
    modality: 'skills',
    power_zone: null,
    power_pct_low: null,
    power_pct_high: null,
    tss_estimate: 55,
    rpe_target: 6,
    duration_mins: 60,
    valid_phases: ['Base', 'Build', 'Peak'],
    warmup: '15min',
    main_set: '45min sand entry, momentum maintenance, exit practice. Tyre pressure experiments.',
    cooldown: '10min',
    coaching_notes: 'Lower tyre pressure (20-22psi) helps in sand. Entry speed is everything.',
    requires_turbo: false,
    requires_wattbike: false,
    requires_power_meter: false,
    requires_cx_terrain: true,
    is_active: true,
  },
  {
    slug: 'skills-mud-riding',
    name: 'Mud Riding Technique',
    modality: 'skills',
    power_zone: null,
    power_pct_low: null,
    power_pct_high: null,
    tss_estimate: 55,
    rpe_target: 7,
    duration_mins: 65,
    valid_phases: ['Build', 'Peak'],
    warmup: '15min',
    main_set: '45min mud riding technique: line choice, momentum, body position over rear wheel.',
    cooldown: '10min',
    coaching_notes: 'Mud riding is a British/Belgian CX speciality. More body weight over rear.',
    requires_turbo: false,
    requires_wattbike: false,
    requires_power_meter: false,
    requires_cx_terrain: true,
    is_active: true,
  },

  // ─── SKILLS — FULL CIRCUIT (3) ───────────────────────────────────────────────
  {
    slug: 'skills-circuit-basic',
    name: 'CX Skills Circuit (Basic)',
    modality: 'skills',
    power_zone: null,
    power_pct_low: null,
    power_pct_high: null,
    tss_estimate: 55,
    rpe_target: 5,
    duration_mins: 80,
    valid_phases: ['Foundation', 'Base'],
    warmup: '15min easy',
    main_set: '60min full CX skills circuit at low speed: barriers, sand, corners, dismounts, run-up. Quality focus.',
    cooldown: '10min easy',
    coaching_notes: 'Low speed full circuit builds muscle memory without pressure.',
    requires_turbo: false,
    requires_wattbike: false,
    requires_power_meter: false,
    requires_cx_terrain: true,
    is_active: true,
  },
  {
    slug: 'skills-circuit-race-speed',
    name: 'CX Skills Circuit (Race Speed)',
    modality: 'skills',
    power_zone: null,
    power_pct_low: null,
    power_pct_high: null,
    tss_estimate: 90,
    rpe_target: 8,
    duration_mins: 90,
    valid_phases: ['Build2', 'Peak'],
    warmup: '20min',
    main_set: '60min full circuit at race speed. Timed laps. Compare against previous sessions.',
    cooldown: '15min easy',
    coaching_notes: 'Race speed circuit reveals where time is lost. Video if possible.',
    requires_turbo: false,
    requires_wattbike: false,
    requires_power_meter: false,
    requires_cx_terrain: true,
    is_active: true,
  },
  {
    slug: 'skills-circuit-pre-race',
    name: 'Pre-Race Skills Warm-Up',
    modality: 'skills',
    power_zone: null,
    power_pct_low: null,
    power_pct_high: null,
    tss_estimate: 35,
    rpe_target: 5,
    duration_mins: 35,
    valid_phases: ['Taper', 'Peak'],
    warmup: 'natural',
    main_set: '30min pre-race skills warm-up circuit at moderate pace. All technical elements included.',
    cooldown: 'natural',
    coaching_notes: 'Pre-race only. Activates skills without fatigue. Never push hard here.',
    requires_turbo: false,
    requires_wattbike: false,
    requires_power_meter: false,
    requires_cx_terrain: true,
    is_active: true,
  },
]
